# services.yaml
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  namespace: nestjs-production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  selector:
    app: nestjs-backend
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nestjs-production
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: nestjs-production
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379